#!/usr/bin/env php
<?php
/**
 * @todo adds a description (license text, description of this class / file, etc)
 */
/**
 * Cronjob console
 *
 * Type `console list` for all commands
 */

require_once __DIR__ . '/Bootstrap.php';

use Symfony\Component\Console\Application;
use TYPO3Analysis\Command\GetTYPO3OrgCommand;
use TYPO3Analysis\Command\ConsumerCommand;

$console = new Application();
$console->add(new GetTYPO3OrgCommand());
$console->add(new ConsumerCommand());
$console->run();