#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'git'
cookbook 'python'

cookbook "repositoryhandler",
	:github => "andygrunwald/chef-repositoryhandler"

cookbook "cvsanaly",
	:github => "andygrunwald/chef-cvsanaly"

cookbook 'mysql'
cookbook 'rabbitmq'
cookbook 'php'
cookbook 'jolicode-php'
cookbook 'composer'

cookbook "typo3analytics",
	:github => "andygrunwald/chef-typo3analytics"