#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'vim'
cookbook 'git'
cookbook 'python'

cookbook "repositoryhandler",
	:git => "https://github.com/andygrunwald/chef-repositoryhandler",
	:ref => "master"

cookbook "cvsanaly",
	:git => "https://github.com/andygrunwald/chef-cvsanaly",
	:ref => "master"

cookbook 'mysql'
cookbook 'rabbitmq'
cookbook 'php'
cookbook 'composer'

cookbook "typo3analytics",
	:git => "https://github.com/andygrunwald/chef-typo3analytics",
	:ref => "master"

cookbook "github-linguist",
	:git => "https://github.com/andygrunwald/chef-github-linguist",
	:ref => "master"

cookbook "supervisor",
	:git => "https://github.com/andygrunwald/supervisor",
	:ref => "develop"
	# Activate the original repository if the bug was fixed
	# https://github.com/opscode-cookbooks/supervisor/pull/19
	#:git => "https://github.com/opscode-cookbooks/supervisor",
	#:ref => "master"