#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'git'
cookbook 'python'
#cookbook 'jolicode-php'
#cookbook 'mysql'
#cookbook 'phploc'

#cookbook 'php',
#	:github => 'jolicode/chef-cookbook-php'
	#:path => 'Chef/cookbooks'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
