#!/usr/bin/env php
<?php
/**
 * @todo adds a description (license text, description of this class / file, etc)
 */
/**
 * Cronjob console
 *
 * Type `console list` for all commands
 */

require_once __DIR__ . '/Bootstrap.php';

use Symfony\Component\Console\Application;
use TYPO3Analysis\Command\GetTYPO3OrgCommand;
use TYPO3Analysis\Command\ListConsumerCommand;
use TYPO3Analysis\Command\ListProjectsCommand;
use TYPO3Analysis\Command\ConsumerCommand;
use TYPO3Analysis\Command\GitwebCommand;
use TYPO3Analysis\Command\GerritCommand;
use TYPO3Analysis\Command\NNTPCommand;

$console = new Application();
$console->add(new GetTYPO3OrgCommand());
$console->add(new ConsumerCommand());
$console->add(new ListConsumerCommand());
$console->add(new ListProjectsCommand());
$console->add(new GitwebCommand());
$console->add(new GerritCommand());
$console->add(new NNTPCommand());
$console->run();