#!/usr/bin/env php
<?php
/**
 * This file is part of the Jacobine package.
 *
 * (c) Andreas Grunwald <andygrunwald@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * Cronjob console
 *
 * Type `console list` for all commands
 */

// TODO Remove this constant!!
define('CONFIG_FILE', __DIR__ . '/Config/config.yml');

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/app/AppKernel.php';

$kernel = new \Jacobine\AppKernel();
$kernel->run();
